config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup',   to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
    resources :attendances, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :department, length: { in: 3..50 }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include AttendancesHelper
  
  def hello
      render html:"Hello,World!"
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
 def create
  @user = User.find(params[:user_id])
  @attendance = @user.attendances.find_by(worked_on: Date.today)
  if @attendance.started_at.nil?
    @attendance.update_attributes(started_at: current_time)
    flash[:info] = 'おはようございます。'
  elsif @attendance.finished_at.nil?
    @attendance.update_attributes(finished_at: current_time)
    flash[:info] = 'おつかれさまでした。'
  else
    flash[:danger] = 'トラブルがあり、登録出来ませんでした。'
  end
  redirect_to @user
 end
 
  def edit
    @user = User.find(params[:id])
    @first_day = first_day(params[:date])
    @last_day = @first_day.end_of_month
    @dates = user_attendances_month_date
  end
  
  def update
    @user = User.find(params[:id])
    if attendances_invalid?
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes(item)
      end
      flash[:success] = '勤怠情報を更新しました。'
      redirect_to user_path(@user, params:{first_day: params[:date]})
    else
      flash[:danger] = "不正な時間入力がありました、再入力してください。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end
  
   private
    def attendances_params
      params.permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_back_or user
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
    else
      # エラーメッセージ用のflashを入れる
      # 実装はまだ完了していません
      flash.now[:danger] = 'メールアドレスとパスワードの情報が一致しませんでした。'
      render 'new'
    end
  end
  
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :edit_basic_info, :update_basic_info]
  
  def index
    @users = User.paginate(page: params[:page])
  end

   def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
   end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  @user = User.find(params[:id])
  end
  
  def update_basic_info
  @user = User.find(params[:id])
   if @user.update_attributes(basic_info_params)
    flash[:success] = "基本情報を更新しました。"
    redirect_to @user   
   else
    render 'edit_basic_info'
   end
  end

  private

    def user_params
     params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end

    # beforeアクション

    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

     # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
     # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    def basic_info_params
    params.require(:user).permit(:basic_time, :work_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとにタイトルを返す。
  def full_title(page_title = "") # メソッド名と引数の定義
    base_title = "勤怠管理システム" # 変数に代入
    if page_title.empty? # 引数の論理値確認
      base_title # page_titleが空（""）の時は既に定義してあるbase_titleを返す
    else
      page_title + " | " + base_title # 文字列を結合して返す
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def current_time
    Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      Time.now.hour,
      Time.now.min, 0
    )
  end
  
  def working_times(started_at, finished_at)
    format("%.2f", (((finished_at - started_at) / 60) / 60.0))
  end
  
   def working_times_sum(seconds)
    format("%.2f", seconds / 60 / 60.0)
   end
   
   def first_day(date)
    !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
   end

   def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
   end
   
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at].to_s > item[:finished_at].to_s
        attendances = false
        break
      end
    end
    attendances
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 引数に渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (ただし、いる場合のみ)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
   # 記憶しているURL (もしくはデフォルト値) にリダイレクトする
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを記憶しておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # 基本時間などの値を、指定の書式にフォーマットして返す
 def format_basic_time(datetime)
  format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
 end
end

app/views/attendances/edit.html.erb
<% provide(:title, "勤怠編集" ) %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_for(@user, url: update_attendances_path, method: :patch) do |f| %>
    <table class = "table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
     <tbody>
        <% @dates.each do |day| %>
          <%= fields_for "attendances[]", day do |af| %>
            <tr>
              <td><%= day.worked_on.to_s(:date) %></td>
              <td><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
              <td><%= af.time_field :started_at, class: "form-control" %></td>
              <td><%= af.time_field :finished_at, class: "form-control" %></td>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <td><%= af.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
   <div class="btn-attendances-update">
      <%= f.submit "更新", class: "btn btn-primary" %>
      <%= link_to "キャンセル", user_path(@user, params:{first_day: @first_day }), class: "btn btn-default btn-block" %>
    </div>
    <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠管理システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "ユーザ一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー勤怠情報表示", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %> <!-- HTML shimがこの1行で済む -->
  </head>
  <body>
    <%= render 'layouts/header' %> <!-- headerの内容がこの1行で収まる -->
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "ホーム") %>
<div class="center jumbotron">
  <h1>勤怠管理システム</h1>
  <%= link_to "アカウント作成", '/signup', class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :department %>
  <%= f.text_field :department, class: 'form-control' %>


  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
  
 

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    ｜<%= link_to "基本情報編集", basic_info_path(user) %>
    | <%= link_to "削除", user, method: :delete,
                         data: { confirm: "削除してよろしいですか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新する') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :basic_time %>
      <%= f.time_field :basic_time, class: 'form-control' %>

      <%= f.label :work_time %>
      <%= f.time_field :work_time, class: 'form-control' %>

      <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>
<h1>ユーザ一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<% provide(:button_text, '作成する') %>
<h1>ユーザー作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month }),
                         class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %>　時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month }),
                         class: "btn btn-xs btn-primary" %>
      </td>
      <td>指定勤務時間　<%= format_basic_time(@user.work_time) %></td>
      <td>基本時間　<%= format_basic_time(@user.basic_time) %></td>
      <td>初日　<%= @first_day.to_s(:date) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締日　<%= @last_day.to_s(:date) %></td>
    </tr>
  </table>

  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>

  <table class = "table-bordered table-striped table-condensed">
    <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th rowspan = "2">日付</th>
        <th rowspan = "2">曜日</th>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
          <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
          <td><%= day.started_at.to_s(:min) if day.started_at.present? %></td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.to_s(:min) if day.finished_at.present? %></td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %>
              <% seconds = (day.finished_at - day.started_at).to_i %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan = "2"><%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td colspan = "6"></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>